export const TICKET_DISCOVERY_HANDLERS_KEY = 'TICKET_DISCOVERY_HANDLERS_KEY';
export const TICKET_PUBLISHER_KEY = 'TICKET_PUBLISHER_KEY'
export const TICKET_SUBSCRIBER_KEY = 'SUBSCRIBER_KEY'

export const TICKET_CHANNEL = 'TICKET_CHANNEL';
export const TICKET_UNSUBSCRIBE_CHANNEL = 'TICKET_UNSUBSCRIBE_CHANNEL';
export const TICKET_UNSUBSCRIBE_ALL_CHANNEL = 'TICKET_UNSUBSCRIBE_ALL_CHANNEL';
export const TICKET_PERCENTAGE_OPTIONS = 'TICKET_PERCENTAGE_OPTIONS'